const Actions = {
    SET_SEARCH_OPTION: "SET_SEARCH_OPTION",
    SET_SORT_ORDER_OPTION: "SET_SORT_ORDER_OPTION",
    SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
    CHOOSE_SEARCH_BTN_STYLE: "CHOOSE_SEARCH_BTN_STYLE",
    CHOOSE_SORT_BTN_STYLE: "CHOOSE_SORT_BTN_STYLE",
    SET_SEARCH_MOVIES: "SET_SEARCH_MOVIES",
    SET_DETAIL_MOVIES: "SET_DETAIL_MOVIES",
    SET_MOVIE_BY_ID: "SET_MOVIE_BY_ID",
    SET_ERROR: "SET_ERROR",
    SET_ERROR_INFO: "SET_ERROR_INFO"
}

export default Actions;