const Content = {
    HEADER_SEARCH: "FIND YOUR MOVIE",
    SEARCH_BTN: "SEARCH",
    OPTION_SEARCH_LEFT_BTN: "TITLE",
    OPTION_SEARCH_RIGHT_BTN: "GENGRE",
    OPTION_SEARCH_SPAN: "SEARCH BY",
    OPTION_SORT_LEFT_BTN: "RELEASE DATE",
    OPTION_SORT_RIGHT_BTN: "RATING",
    OPTION_SORT_SPAN: "ORDER BY",
    SEARCH_COUNT: "movie found",
    SEARCH_GENRE_LABEL_START: "Films by",
    SEARCH_GENRE_LABEL_END: "genre",
    MOVIE_YEAR_LABEL: "year",
    MOVIE_RUNTIME_LABEL: "min",
    EMPTY_MOVIES_RESULT: "No films found"
}

export default Content;